// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9uFJTiFRcplWrRJtH3guACSgbbsI09oc',
    appId: '1:719482587533:web:4845113f50e1d5d1a655c4',
    messagingSenderId: '719482587533',
    projectId: 'libre-quiz',
    authDomain: 'libre-quiz.firebaseapp.com',
    storageBucket: 'libre-quiz.appspot.com',
    measurementId: 'G-XBDSYPTE13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcgx7C6NXoKgppoeK3neKirJLU81uRMGQ',
    appId: '1:719482587533:android:b49b7ff9f3bbc39ba655c4',
    messagingSenderId: '719482587533',
    projectId: 'libre-quiz',
    storageBucket: 'libre-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa6DW02EYmOKwHdXtpKUWqInfGMsc7aqI',
    appId: '1:719482587533:ios:2986da314da30003a655c4',
    messagingSenderId: '719482587533',
    projectId: 'libre-quiz',
    storageBucket: 'libre-quiz.appspot.com',
    iosBundleId: 'com.example.libreQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa6DW02EYmOKwHdXtpKUWqInfGMsc7aqI',
    appId: '1:719482587533:ios:2986da314da30003a655c4',
    messagingSenderId: '719482587533',
    projectId: 'libre-quiz',
    storageBucket: 'libre-quiz.appspot.com',
    iosBundleId: 'com.example.libreQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9uFJTiFRcplWrRJtH3guACSgbbsI09oc',
    appId: '1:719482587533:web:1cb2a066935da337a655c4',
    messagingSenderId: '719482587533',
    projectId: 'libre-quiz',
    authDomain: 'libre-quiz.firebaseapp.com',
    storageBucket: 'libre-quiz.appspot.com',
    measurementId: 'G-3YT2EHLW58',
  );
}